js/index.js

ESP Matter team has configured their CI job to generate example binaries and config toml file which can used for launchpad UI.
We should have a simpler way to load these from our internal product teams
Added a query parameter support 'solution' which expects values as either 'matter' or 'rainmaker'. Defaults to rainmaker config otherwise.
/?solution=matter
Users can still use their own config toml file by passing the flashConfigURL query param

Allow easier way to load matter config toml file

---

js/index.js

The relative config path was working on local dev. Had to fix the pathname as per the deployed generic one.

fix the path for default rainmaker config

---

package-lock.json
package.json

* Update esptool-js to [release 0.2.2](https://github.com/espressif/esptool-js/releases/tag/v0.2.2):
* [Update stubs from esptool.py v4.6.1](https://github.com/espressif/esptool-js/pull/98)
Over at https://github.com/espressif/esp-launchpad/issues/18#issuecomment-1633964597 it was reported that this fixes #18.

feat(deps): update esptool-js to 0.2.2

---

js/index.js
minimal-launchpad/index.html
minimal-launchpad/minimal_ui_index.js
minimal-launchpad/minimal_ui_styles.css

- Add feature of **Minimal Launchpad** that works with **multipart support** and **markdown parsing** to show _information about product_.
- Implements fix based on suggestions provided by @sachinkosare in issue #32.
- Add **"scrollback"** parameter to resolve the issue of **losing previous logs for large outputs** on the _xterm terminal window_. Special thanks to @dhavalgujar for the assistance with this issue.
To work with the **minimal Launchpad**, the following **TOML format** should be provided as URL to **_flashConfigURL_** **query parameter**:
> esp_toml_version = 1.0
> multipart = true
> chip = "_<YOUR_CHIP_NAME>_"
> supported_apps = ["_<YOUR_FIRMWARE_APP_NAME>_"]
> [_<YOUR_FIRMWARE_APP_NAME>_]
> readme.text = ["_<YOUR_PRODUCT_INFORMATION_MARKDOWN>_"]
> …

Feature: Add Minimal Launchpad.

---

config/default_config.toml
config/matter_config.toml
config/rainmaker_config.toml

- Update the IOS app URL for matter solution. Now that a single ESP Rainmaker IOS App supports Rainmaker plus matter fabric devices.
- Also removed spaces in the app names, replaced with hiphen.

Update the IOS app URL for matter solution.

---

minimal-launchpad/minimal_ui_index.js

- It introduces a check to handle an empty README.md file that was causing UI distortion.
- It corrects the display of results, showing only the **terminalContainer** and hiding the **productInfoContainer**.

Fix: Added Check For Empty README.md File [ minimal-launchpad ]

---

index.html
js/index.js

This merge request introduces support for displaying a setup payload logo and QR code in the launchpad after flashing, provided they are specified through the following TOML parameters in the given TOML file passed to _**flashConfigURL**_ query parameter:
```
setup_payload_logo = "<_YOUR_SETUP_PAYLOAD_LOGO_LINK_>"
setup_payload = "<_YOUR_SETUP_PAYLOAD_QR_CODE_LINK_>"
```
@adwait-esp, please take a look at the working demo [here](https://rushikeshpatange.github.io/esp-launchpad/?flashConfigURL=https://raw.githubusercontent.com/RushikeshPatange/setupPayloadTOML/main/testToml.toml)

Feature Added Support For Setup Payload Logo And Qrcode

---

js/index.js

This PR adds an option to filter shown examples in the dropdown menu by adding `app` URL parameter handling.
This could be useful when used with `flashConfigURL` to selectively display examples when the user clicks on a link in the README file belonging to a particular example in the github repo.

feat: Add the option to filter an example name in the url parameters

---

README.md
config/config.toml

This PR makes the following enhancements:
- Updates the README.md to indicate that ESP Launchpad now supports displaying markdown content, allowing users to add additional information about the application after flashing.
- Updates the config.toml file to add parameters/fields that provide the above support per app.
You can take a look on updated README.md and config.toml file on my branch [docs/update_readme_and_config_toml](https://github.com/RushikeshPatange/esp-launchpad/tree/docs/update_readme_and_config_toml)

Enhancement/docs: Updated README.md And config.toml File.

---

minimal-launchpad/minimal_ui_index.js

- This PR adds a call to **esploader.erase_flash** to remove existing binaries from the chipset before initiating the flashing of new binaries.
https://rushikeshpatange.github.io/esp-launchpad/minimal-launchpad/

Added Functional Call To "erase_flash" In Minimal Launchpad

---

minimal-launchpad/index.html
minimal-launchpad/minimal_ui_index.js
package-lock.json
package.json

This PR adds support to interact with flashed firmware by passing commands through CLI in minimal-launchpad, which get enabled when passed TOML has following field: (i.e.,  portConnectionOptions)
```
** Note: This is just an example **
[[portConnectionOptions]]
baudRate = 48600 (number)
dataBits = 8 (number)
stopBits = 1 (number)
parity = "none" (ParityType)
flowControl = "none" (FlowControlType)
```
The options below to portConnectionOptions are passed while opening the port of the device. You can find more about serialOptions [here](https://wicg.github.io/serial/#serialoptions-dictionary)
You can check the working demo from following URL:
```
https://esp-launchpad-cli.netlify.app/minimal-launchpad/?flashConfigURL=<YOUR_TOML_FILE_LINK_WITH_ABOVE_FIELD>
```

Feat/CLI : Add Support For CLI In Minimal-Launchpad

---

js/index.js
minimal-launchpad/minimal_ui_index.js

- It ensures that baudrate and offset/address are of the required type.
- It resolves the issue of incorrectly printing offsets during flashing. Previously, the offset/address were passed as strings instead of numbers, causing problems with the printing of offsets.
Incorrectly Printed Offsets:
Test link ?
- [Incorrectly Printed Offsets](https://espressif.github.io/esp-launchpad/minimal-launchpad/?flashConfigURL=https://raw.githubusercontent.com/RushikeshPatange/EZC_toml/main/EZC/config.toml)
- [Fix](https://rushikeshpatange.github.io/esp-launchpad/minimal-launchpad/?flashConfigURL=https://raw.githubusercontent.com/RushikeshPatange/EZC_toml/main/EZC/config.toml)

Fix: Resolve Issue With Passing Correct Variable Type Of Baudrate And Offset.

---

js/utils.js

What Does This PR Do ?
- This PR add's support for FT232R: FTDI chip by adding related **VendorID:0x0403** and **ProductID:0x6001**

Support/FT232R: Add Support For FT232R(FTDI chip)

---

config/config.toml
js/index.js
minimal-launchpad/minimal_ui_index.js
package-lock.json
package.json

- Upgrade esptool-js version.
- Handle breaking API changes caused due to upgradation.
- Add support for proper console baudrate for chips with 26 MHz frequency.
- Add support of providing console baudrate through TOML.
You can test the changes by connecting your C2 Devkit to the launchpad [here](https://rushikeshpatange.github.io/esp-launchpad/) :-)

Support: Add Support Of Proper Console Baudrate For Chips With 26 MHz  Frequency

---

minimal-launchpad/minimal_ui_index.js

- Minimal-launchpad now uses common default baudrate to flash expresslink chips as like other chips rather than using baudrate coming from toml  in portConnectionOptions objects array which was lesser than the default one, making it slower to flash expresslink chips.
You can test the above fix [here](https://rushikeshpatange.github.io/esp-launchpad/minimal-launchpad/?flashConfigURL) by providing **supported expresslink TOML** to flashConfigURL parameter.
How you can verify the baudrate has been set to default value ?
- You will see one log in console saying **Changing baudrate to 460800**

Fix(minimal-launchpad): Fix Slower Flashing of Expresslink Chips

---

minimal-launchpad/minimal_ui_index.js

-  Rename Console Baudrate Key  from baudRate to console_baudrate_key, come's under portConnectionOptions of ExL TOML file
You can test the above changes [here](https://esp-launchpad.netlify.app/minimal-launchpad/?flashConfigURL=) by providing ExL TOML to flashConfigURL query param.

Fix: Rename Console Baudrate Key

---

index.html
js/index.js

- Add supports for console baudrate selection in settings tab.
- Handle different scenarios for resetting the device using console baudrate.
- Update copyright year in footer.
| Before | After |
| ---- | ---- |
|![Before](https://github.com/espressif/esp-launchpad/assets/90703337/ac917c2d-a3b6-42c6-a264-80d3c43fd0ef)|![image](https://github.com/espressif/esp-launchpad/assets/90703337/ccf92cc8-ed09-491a-afbd-d6c3caedba03)|
You can test the above changes [here](https://rushikeshpatange.github.io/esp-launchpad/).
- If user try to reset the device without flashing it through any mode ( QuickTry, DIY ), user will able to configure console baudrate from settings tab dropdown.
- If user first flashed through QuickTry mode then there are following 2 scenario's:
- console_baudrate provided in …

Support: Add Support For Console Baudrate Selection

---

config/config.toml
css/custom.css
index.html
js/index.js

This PR adds following feature:
- This PR enables Markdown display support on the default launchpad on **Quick Start** page that shows the configuration on which the applications are built.
> Note: Your config file should be of following format where _config_readme_url_ used to display config on  **Quick Start** page
```
https://rushikeshpatange.github.io/esp-launchpad/?flashConfigURL=<YOUR_CONFIG_FILE_URL>
```
```
esp_toml_version = 1.0
firmware_images_url = "<URL to your firmware images directory>"
supported_apps = ["YOUR_FIRMWARE_APP_NAME"]
config_readme_url = "<APP_CONFIG_README_FILE_URL>"
[YOUR_FIRMWARE_APP_NAME]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "SINGLE_BIN_FOR_ESP32.bin"
image.esp32-s2 = "SINGLE_BIN_FOR_ESP32-S2.bin"
image.esp32-c3 = …
```

Feat: Show Application Configuration On Quick Start Page

---

package-lock.json
package.json

- It will update the esptool-js package version to 0.4.5 which will add support for P4 chips.
- https://rushikeshpatange.github.io/esp-launchpad/

Update Esptool-js Version to v0.4.5

---

config/config.toml
css/custom.css
index.html
js/index.js

This version includes the following additions:
1. Optional: Added ESP Develop Kits options for each Application. 
Different development board models such as esp-box and esp-box3 are displayed based on the selected chipset.
2. Optional: Added a description field for each Application.
This field allows for a brief introduction of the BIN file, including project links and more.
3. Optional: Integrated README.md rendering below each Application.
Previously, this feature was only displayed after flashing.

feat(launchpad): add launchpad support devkit and readme

---

package-lock.json
package.json

- It will update the esptool-js package version to 0.4.6 which will add support for C5 chips.
- https://rushikeshpatange.github.io/esp-launchpad/

Update esptool-js to v0.4.6

---

package-lock.json
package.json

- It will update the esptool-js package version to 0.4.7 which will add support for C61 chips and fix bug related to C5 eco1 magic number ([Reference](https://github.com/espressif/esptool-js/releases/tag/v0.4.7))
- https://rushikeshpatange.github.io/esp-launchpad/

update esptool-js to v0.4.7

---

config/rainmaker_config.toml

Feedback was received, that for better user experience it would be good to include description for the example RainMaker projects available to try out on the ESP chipsets.
This change includes adding reference to readme files for each of the RainMaker example projects

Add reference to readme files for each of the RainMaker example projects

---

js/index.js

RainMaker CI/CD job generates firmware images (combined into one single binary) for each of the examples. A toml file is also auto-generated for these supported examples. This change makes use of the generated toml file which in turn makes use of the generated latest firmware images.

Make use of the rainmaker example firmware images build from the GitHub

---

js/index.js

Modified function `downloadAndFlash` to handle image offset.
Image offset should be added to config.toml inside the section of the corresponding app. If offset is not specified it defaults to zero.
Also, added an alert if the image file is not found, because otherwise there is no warning to the user (but this should also be handled outside this function, to disable the flashing complete message).
Fixes #48 (Add a way to specify an offset in config.toml)
Example of (partial) config.toml, with offset 0x10000:
```
supported_apps = ["example_app"]
...
[example_app]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3", "ESP32-S3"]
offset = "0x10000"
image.esp32 = "example.bin"
```
Remove alert when image file not found, and handle it outside this function.

Allowing image offset to be specified in config.toml (fixes issue #48)

---

js/index.js
package-lock.json
package.json

- Upgrade esptool-js to the 0.5.4 for improved compatibility of devices and performance.
- Enhanced device data reading functionality needed on resetting device.
- After upgrading **esptool-js** version in **esp-launchpad** there was an issue while resetting the device, which will get fix by this PR.
| Test Link | Tested Chips |
|-----------|-------------|
| [ESP Launchpad](https://rushikeshpatange.github.io/esp-launchpad/) | - ESP32-C3<br>- ESP32-C61 |
---
Ensured the following points:

Update esptool-js to v0.5.4

---

js/index.js

**Problem**
- The existing app filtering logic in buildQuickTryUI() was filtering supported_apps based on a pattern match using startsWith() containing a '-'.
- As a result, only apps whose names followed a specific prefix pattern were being retained, and valid apps not matching this pattern were unintentionally excluded from the selection.
**Change Overview**
- Removed the '-' from the filtering logic to more generically support filtering.
- Now, when an app value is passed via the URL, the UI will filter supported_apps by exact match or the apps starting with a particular pattern. So, apps not having a '-' will also get filtered correctly.
- If no matching app is found, an alert is shown indicating that no applications were found for the requested app name.
**Testing**
- Tested locally …

Remove the '-' from app filtering logic to support more generic app filtering .
